- name: Setup Pleroma DB
  hosts: brighid.xeno
  become: yes
  vars_prompt:
    - name: db_password
      prompt: Database password
  tasks:
    # Setup DB
    - name: Ensure psycopg2 is installed
      community.general.pacman:
        name: python-psycopg2
        state: present

    - name: Ensure DB user exist
      community.postgresql.postgresql_user:
        name: pleroma
        password: "{{ db_password }}"
        role_attr_flags: CREATEDB

    - name: Create a Pleroma DB
      community.postgresql.postgresql_db:
        name: pleroma
        owner: pleroma

    - name: Adds extensions 1
      community.postgresql.postgresql_ext:
        name: citext
        db: pleroma
    - name: Adds extensions 2
      community.postgresql.postgresql_ext:
        name: pg_trgm
        db: pleroma
    - name: Adds extensions 3
      community.postgresql.postgresql_ext:
        name: "uuid-ossp"
        db: pleroma
