download_dir = "/mnt/stuff/downloads/you-dump"
ydl_exec = "yt-dlp"
static_dir = "/var/lib/you-dump/static"
listen_address = "0.0.0.0"
listen_port = 8321
log_timestamp = false
extra_args = ["--windows-filenames", "--restrict-filenames", "--write-subs", "--write-auto-subs", "--embed-subs", "--compat-options", "no-keep-subs", "--embed-metadata"]
