- name: Build package
  hosts: amalthus.xeno
  vars:
    pkg: baregit
  tasks:
    - name: Download source
      ansible.builtin.git:
        repo: "https://github.com/MetroWind/{{ pkg }}"
        dest: "~/pkgs/{{ pkg }}"

    - name: Build package
      ansible.builtin.command:
        cmd: "makepkg -sr --noconfirm -f"
        chdir: "/home/user/pkgs/{{ pkg }}/packages/arch"
        creates: "/home/user/pkgs/{{ pkg }}/packages/arch{{ pkg }}-git-*-any.pkg.tar.zst"

    - name: What package did I build?
      register: package_file_proc
      ansible.builtin.shell:
        cmd: "ls -1 {{ pkg }}-*-any.pkg.tar.zst | head -n1"
        chdir: "/home/user/pkgs/{{ pkg }}/packages/arch"

    - set_fact:
        package_file: "{{ package_file_proc.stdout }}"

    - debug:
        msg: "Built package {{ package_file }}"

    - name: Fetch package to local
      ansible.builtin.fetch:
        src: "/home/user/pkgs/{{ pkg }}/packages/arch/{{ package_file }}"
        dest: /tmp/
        flat: yes

    - name: Remove build files
      ansible.builtin.file:
        path: "/home/user/pkgs/{{ pkg }}"
        state: absent

- name: Deploy
  hosts: brighid.xeno
  become: yes
  vars:
    package_file: "{{ hostvars['amalthus.xeno']['package_file'] }}"
    client_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66326362393937386561343039613733303363616338343563333531623863373332313732336564
          6231343564353537343739303237643165346663626434370a663736346264393036353934356635
          31383065383861623733303633383836646333656463316131396634333164363430623336353936
          6664313863343735360a363232323763376162363333366331643131663165383739666262326137
          33613634333834623362663664613035353130623730333062653462333138663636306566636162
          6639613135313462393736393738313436383236383733333231
  tasks:
    - name: Copy package to remote
      ansible.builtin.copy:
        src: "/tmp/{{ package_file }}"
        dest: /tmp/

    - name: Install package
      community.general.pacman:
        name: "/tmp/{{ package_file }}"
        state: present

    - name: Copy config
      ansible.builtin.template:
        src: baregit.ini
        dest: /etc/baregit.ini
        group: baregit
        owner: baregit
        mode: 0600

    - name: Copy Apache config
      ansible.builtin.copy:
        src: httpd.conf
        dest: /etc/httpd/conf/extra/git.conf

    - name: Enable vhost
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#Include\s+conf/extra/git\.conf'
        insertafter: "Probably not exists"
        line: 'Include conf/extra/git.conf'

    - name: Restart Apache
      ansible.builtin.systemd:
        state: restarted
        name: httpd
        enabled: yes

    - name: Make sure service is running and enabled
      ansible.builtin.systemd:
        state: restarted
        name: baregit
        enabled: yes
        daemon_reload: yes

    - name: Remove package file
      ansible.builtin.file:
        path: "/tmp/{{ package_file }}"
        state: absent
