---
- name: Set DNS servers
  hosts: arch
  become: yes
  tasks:
    - name: Copy config file
      ansible.builtin.copy:
        src: resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '644'
