---
- name: All hosts up-to-date
  hosts: localhost
  tasks:
    - name: Create new container snapshot
      community.general.proxmox_snap:
        api_user: root@pam
        api_password: 2w0rldsntwoSuns
        api_host: xeno.xeno
        vmid: 108
        state: present
        snapname: pre-updates
