- name: Deploy MeTube
  hosts: ssh.mws.rocks
  become: yes
  vars_prompt:
    - name: upload_password
      prompt: Password required for video upload
  tasks:
    - name: Download binary
      ansible.builtin.get_url:
        url: "https://github.com/MetroWind/metube/releases/latest/download/metube-linux-amd64.xz"
        dest: /tmp/metube.xz
        mode: '0644'

    - name: Extract binary
      ansible.builtin.command:
        cmd: unxz /tmp/metube.xz
        creates: /tmp/metube

    - name: Move binary to PATH
      ansible.builtin.command:
        cmd: mv /tmp/metube /usr/local/bin/metube

    - name: Make the binary executable
      ansible.builtin.file:
        path: /usr/local/bin/metube
        mode: '0755'

    - name: Copy user definition
      ansible.builtin.copy:
        src: tube.sysusers
        dest: /etc/sysusers.d/tube.conf

    - name: Create user
      ansible.builtin.command: systemd-sysusers

    - name: Copy config
      ansible.builtin.template:
        src: config.toml
        dest: /etc/metube.toml
        group: tube
        owner: tube
        mode: 0600

    - name: Copy service file
      ansible.builtin.copy:
        src: metube.service
        dest: /etc/systemd/system/
        mode: 0644

    - name: Create working dir
      ansible.builtin.file:
        path: /var/lib/metube
        state: directory
        mode: '0755'
        owner: tube
        group: tube

    - name: Create video dir
      ansible.builtin.file:
        path: /var/lib/metube/videos
        state: directory
        mode: '0755'
        owner: tube
        group: tube

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/MetroWind/metube.git'
        dest: /tmp/metube
        version: master

    - name: Copy templates
      ansible.builtin.copy:
        remote_src: true
        src: "/tmp/metube/templates"
        dest: "/var/lib/metube"
        group: tube
        owner: tube

    - name: Copy statics
      ansible.builtin.copy:
        remote_src: true
        src: "/tmp/metube/static"
        dest: "/var/lib/metube"
        group: tube
        owner: tube

    - name: Copy Apache config
      ansible.builtin.copy:
        src: apache.conf
        dest: /etc/httpd/conf/vhosts/metube.conf

    - name: Enable vhost
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#Include\s+conf/vhosts/metube\.conf'
        insertafter: "Probably not exists"
        line: 'Include conf/vhosts/metube.conf'

    - name: Restart Apache
      ansible.builtin.systemd:
        state: restarted
        name: httpd
        enabled: yes

    - name: Make sure service is running and enabled
      ansible.builtin.systemd:
        state: restarted
        name: metube
        enabled: yes
        daemon_reload: yes

    - name: Remove source code
      ansible.builtin.file:
        path: /tmp/metube
        state: absent
