server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://alvis:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
      host: {{ ansible_hostname }}

- job_name: systemd
  journal:
    json: false
    max_age: 12h
    labels:
      job: systemd
      host: {{ ansible_hostname }}
  relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'
