---
- name: Setup
  hosts: alvis.xeno
  become: yes

  tasks:
    - name: Make sure components are installed
      community.general.pacman:
        name:
         - prometheus
         - grafana
         - loki
        state: present

    - name: Copy config file to remote
      ansible.builtin.template:
        src: config-prometheus.yaml
        dest: /etc/prometheus/prometheus.yml
        owner: root
        group: prometheus
        mode: '640'

    - name: Copy recording rules file to remote
      ansible.builtin.copy:
        src: recording-rules.yaml
        dest: /etc/prometheus/recording-rules.yaml
        owner: root
        group: prometheus
        mode: '640'

    - name: Copy Grafana config to remote
      ansible.builtin.copy:
        src: config-grafana.ini
        dest: /etc/grafana.ini
        owner: grafana
        group: grafana
        mode: '640'

    - name: Copy Loki config to remote
      ansible.builtin.copy:
        src: config-loki.yaml
        dest: /etc/loki/loki.yaml
        owner: root
        group: root
        mode: '644'

    - name: Make sure Prometheus is running and enabled
      ansible.builtin.systemd:
        state: restarted
        name: prometheus
        enabled: yes

    - name: Make sure Loki is running and enabled
      ansible.builtin.systemd:
        state: restarted
        name: loki
        enabled: yes

    - name: Make sure Grafana is running and enabled
      ansible.builtin.systemd:
        state: restarted
        name: grafana
        enabled: yes

- name: Setup VPS
  hosts: darksair.org
  become: yes
  tasks:
    - name: Make sure Promtail is installed
      community.general.pacman:
        name:
          - promtail
        state: present

    - name: Copy Promtail config to remote
      ansible.builtin.copy:
        src: config-promtail-darksair.org.yaml
        dest: /etc/loki/promtail.yaml
        owner: root
        group: root
        mode: '644'

- name: Setup VMs
  hosts: arch
  become: yes

  tasks:
    - name: Make sure prometheus-node-exporter and promtail is installed
      community.general.pacman:
        name:
          - prometheus-node-exporter
          - promtail
        state: present

    - name: Make sure prometheus-node-exporter is running and enabled
      ansible.builtin.systemd:
        state: started
        name: prometheus-node-exporter
        enabled: yes

    - name: Copy Promtail config to remote
      ansible.builtin.template:
        src: config-promtail.yaml
        dest: /etc/loki/promtail.yaml
        owner: root
        group: root
        mode: '644'

- name: Shared setup
  hosts: [arch, darksair.org]
  become: yes
  tasks:
    # Change permission of /var/log/tallylog to suppress some errors
    - name: Change permission of /var/log/tallylog
      file:
        path: /var/log/tallylog
        mode: 0644

    - name: Add Promtail user to the “log” group
      user:
        name: promtail
        append: yes
        groups: log

    - name: Make sure promtail is running and enabled
      ansible.builtin.systemd:
        state: restarted
        name: promtail
        enabled: yes
