- name: Deploy Remark42
  hosts: ssh.mws.rocks
  become: yes
  vars:
    version: "1.13.0"
    secret: "{{ lookup('community.general.random_string', length=16, special=false) }}"
  vars_prompt:
    - name: github_client_secret
      prompt: GitHub client secret
  tasks:
    - name: Create download dir
      ansible.builtin.file:
        path: /tmp/remark42
        state: directory

    - name: Download binary
      ansible.builtin.unarchive:
        src: "https://github.com/umputun/remark42/releases/download/v{{ version }}/remark42.linux-amd64.tar.gz"
        dest: /tmp/remark42
        mode: '0755'
        remote_src: yes

    - name: Copy binary to bin dir
      ansible.builtin.copy:
        src: /tmp/remark42/remark42.linux-amd64
        dest: /usr/local/bin/remark42
        remote_src: yes
        mode: '0755'

    - name: Remove download dir
      ansible.builtin.file:
        path: /tmp/remark42
        state: absent

    - name: Copy user definition
      ansible.builtin.copy:
        src: remark42.sysusers
        dest: /etc/sysusers.d/remark42.conf

    - name: Create user
      ansible.builtin.command: systemd-sysusers

    - name: Copy service file
      ansible.builtin.template:
        src: remark42.service
        dest: /etc/systemd/system/
        mode: 0644

    - name: Create working dir
      ansible.builtin.file:
        path: /var/lib/remark42
        state: directory
        mode: '0755'
        owner: remark42
        group: remark42

    - name: Make sure service is running and enabled
      ansible.builtin.systemd:
        state: restarted
        name: remark42
        enabled: yes
        daemon_reload: yes

    - name: Copy Apache config
      ansible.builtin.copy:
        src: apache.conf
        dest: /etc/httpd/conf/vhosts/remark42.conf

    - name: Enable vhost
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#Include\s+conf/vhosts/remark42\.conf'
        insertafter: "Probably not exists"
        line: 'Include conf/vhosts/remark42.conf'

    - name: Restart Apache
      ansible.builtin.systemd:
        state: restarted
        name: httpd
        enabled: yes
