# Matrix server @obrona
<VirtualHost *:80>
    ServerName matrix.xeno.darksair.org

    RewriteEngine on
    DocumentRoot /srv/http-matrix
    DirectoryIndex index.html

    <Directory /srv/http-matrix>
        Options -Indexes
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>
<VirtualHost *:443 *:8448>
    ServerName matrix.xeno.darksair.org

    SSLCertificateFile /etc/letsencrypt/live/xeno.darksair.org/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/xeno.darksair.org/privkey.pem

    RewriteEngine on
    DocumentRoot /srv/http-matrix
    DirectoryIndex index.html

    <Directory /srv/http-matrix>
        Options -Indexes
        AllowOverride None
        Require all granted
    </Directory>

    ProxyPreserveHost On
    AllowEncodedSlashes NoDecode
    RequestHeader setIfEmpty Access-Control-Allow-Origin "*"
    RequestHeader setIfEmpty Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
    RequestHeader setIfEmpty Access-Control-Allow-Headers "X-Requested-With, Content-Type, Authorization"

    ProxyPass /.well-known/matrix http://obrona.xeno:6167/.well-known/matrix nocanon
    ProxyPassReverse /.well-known/matrix http://obrona.xeno:6167/.well-known/matrix
    ProxyPass /_matrix http://obrona.xeno:6167/_matrix nocanon
    ProxyPassReverse /_matrix http://obrona.xeno:6167/_matrix
    ProxyPass /_continuwuity http://obrona.xeno:6167/_continuwuity nocanon
    ProxyPassReverse /_continuwuity http://obrona.xeno:6167/_continuwuity
</VirtualHost>
