---
- name: Reset Postgres for KeyCloak
  hosts: brighid.xeno
  become: yes

  tasks:
    - name: Ensure psycopg2 is installed
      community.general.pacman:
        name: python-psycopg2
        state: present

    - name: Ensure DB removal
      community.postgresql.postgresql_db:
        name: matrix
        state: absent

    - name: Ensure DB user deletion
      community.postgresql.postgresql_user:
        name: matrix
        state: absent
