- name: Setup Conduit
  hosts: obrona.xeno
  become: yes
  vars:
    branch: next                # next or master
  tasks:
    - name: Download binary
      get_url:
        url: "https://gitlab.com/famedly/conduit/-/jobs/artifacts/{{ branch }}/raw/build-output/linux_amd64/conduit?job=docker:{{ branch }}"
        dest: /usr/local/bin/matrix-conduit
        mode: 0755
    - name: Create sysuser dir
      ansible.builtin.file:
        path: /etc/sysusers.d
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Copy sysusers file
      ansible.builtin.copy:
        src: sysusers-conduit.conf
        dest: /etc/sysusers.d/conduit.conf
        owner: root
        group: root
        mode: '0644'
    - name: Ensure user
      ansible.builtin.systemd:
        state: started
        name: systemd-sysusers
    - name: Create config dir
      ansible.builtin.file:
        path: /etc/matrix-conduit
        state: directory
        owner: conduit
        group: conduit
        mode: '0755'
    - name: Copy config file
      ansible.builtin.copy:
        src: conduit.toml
        dest: /etc/matrix-conduit/conduit.toml
        owner: conduit
        group: conduit
        mode: '0644'
    - name: Copy service file
      ansible.builtin.copy:
        src: conduit.service
        dest: /etc/systemd/system/conduit.service
        owner: root
        group: root
        mode: '0644'
    - name: Create runtime dir
      ansible.builtin.file:
        path: /var/lib/matrix-conduit
        state: directory
        owner: conduit
        group: conduit
        mode: '0750'
    - name: Ensure conduit service is enabled and started
      ansible.builtin.systemd:
        state: restarted
        name: conduit
        enabled: yes
