RewriteEngine on
RewriteOptions InheritDown
RewriteCond %{HTTP_USER_AGENT}  ^.*Amazonbot.*$ [OR]
RewriteCond %{HTTP_USER_AGENT} ^$ [OR]
RewriteCond %{REQUEST_URI} ^/wp-.*
RewriteRule ^ "https://english.www.gov.cn/" [R,L]
