[settings]
album_art_pattern = '(cover|folder)\.(png|jpe?g)$'
# reindex_every_n_seconds = 100

[[mount_dirs]]
name = 'music'
source = '/mnt/music-lossy-copy'

# [[mount_dirs]]
# name = 'other'
# source = 'some/dir'

[[users]]
name = 'admin'
password = '{{ admin_password }}'
admin = true
