---
- name: Setup ComfyUI
  hosts: kosmos.xeno
  become: yes
  tasks:
    - name: Copy sysusers file
      ansible.builtin.copy:
        src: files/comfyui.sysusers
        dest: /usr/local/lib/sysusers.d/comfyui.conf
        owner: root
        group: root
        mode: '0644'
    - name: Ensure user
      ansible.builtin.systemd:
        state: restarted
        name: systemd-sysusers

    - name: Ensure diffusion dir
      ansible.builtin.file:
        path: /opt/stable-diffusion
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Ensure ComfyUI directory
      ansible.builtin.file:
        path: /opt/stable-diffusion/comfyui
        owner: comfyui
        group: comfyui
        mode: 0755
        state: directory

    - name: Clone ComfyUI
      become: yes
      become_user: comfyui
      ansible.builtin.git:
        repo: https://github.com/comfyanonymous/ComfyUI.git
        dest: /opt/stable-diffusion/comfyui/comfyui

    - name: Copy model path config
      ansible.builtin.copy:
        src: files/comfyui-model-path.yaml
        dest: /opt/stable-diffusion/comfyui/comfyui/extra_model_paths.yaml
        owner: comfyui
        group: comfyui
        mode: '0644'

    - name: Install rmbg extension
      become: yes
      become_user: comfyui
      ansible.builtin.git:
        repo: https://github.com/1038lab/ComfyUI-RMBG.git
        dest: /opt/stable-diffusion/comfyui/comfyui/custom_nodes/ComfyUI-RMBG

    - name: Build env
      ansible.builtin.pip:
        name:
          - torch
          - torchvision
          - torchaudio
          - accelerate
        virtualenv: /opt/stable-diffusion/env
        extra_args: "--extra-index-url https://download.pytorch.org/whl/cu126"

    - name: Install dependencies
      ansible.builtin.pip:
        virtualenv: /opt/stable-diffusion/env
        requirements: /opt/stable-diffusion/comfyui/comfyui/requirements.txt

    # For some reason this always get stuck...
    - name: Install RMBG dependencies
      ansible.builtin.command: "xargs -n 1 /opt/stable-diffusion/env/bin/pip install < /opt/stable-diffusion/comfyui/comfyui/custom_nodes/ComfyUI-RMBG/requirements.txt"

    - name: Copy comfyui service file
      ansible.builtin.copy:
        src: files/comfyui.service
        dest: /etc/systemd/system/comfyui.service
        owner: root
        group: root
        mode: '0644'
    - name: Ensure comfyui is started
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted
        name: comfyui
        enabled: yes

# Reverse proxy doesn’t work right on comfyui right now. See
# https://github.com/Comfy-Org/ComfyUI_frontend/issues/5479
#
# - name: Setup HTTP proxy
#   hosts: brighid.xeno
#   become: yes
#   tasks:
#     - name: Copy Apache config
#       ansible.builtin.copy:
#         src: files/http-comfyui.conf
#         dest: /etc/httpd/conf/extra/comfyui.conf

#     - name: Enable vhost
#       ansible.builtin.lineinfile:
#         path: /etc/httpd/conf/httpd.conf
#         regexp: '^#Include\s+conf/extra/comfyui\.conf'
#         insertafter: "Probably not exists"
#         line: 'Include conf/extra/comfyui.conf'

#     - name: Restart Apache
#       ansible.builtin.systemd:
#         state: restarted
#         name: httpd
#         enabled: yes
