---
- name: Download LLM models
  hosts: kosmos.xeno
  become: yes
  tasks:
    - name: Download Gemma 4 26B abliterated model
      ansible.builtin.command:
        argv:
          - wget
          - "-c"
          - "-O"
          - "/mnt/data/models/llm/gemma-4-26B-A4B-it-abliterated-UD-Q4_K_M.gguf"
          - "https://huggingface.co/groxaxo/Huihui-gemma-4-26B-A4B-it-abliterated-GGUF/resolve/main/gemma-4-26B-A4B-it-UD-Q4_K_M.gguf"

    - name: Download Gemma 4 mmproj
      ansible.builtin.command:
        argv:
          - wget
          - "-c"
          - "-O"
          - "/mnt/data/models/llm/gemma-4-mmproj.gguf"
          - "https://huggingface.co/unsloth/gemma-4-26B-A4B-it-GGUF/resolve/main/mmproj-BF16.gguf"

    - name: Download qwen3.8 27B abliterated model
      ansible.builtin.command:
        argv:
          - wget
          - "-c"
          - "-O"
          - "/mnt/data/models/llm/Huihui-Qwen3.8-27B-abliterated-Q4_K.gguf"
          - "https://huggingface.co/huihui-ai/Huihui-Qwen3.8-27B-abliterated-GGUF/resolve/main/Huihui-Qwen3.8-27B-abliterated-Q4_K.gguf"

    - name: Download qwen3.8 27B mmproj
      ansible.builtin.command:
        argv:
          - wget
          - "-c"
          - "-O"
          - "/mnt/data/models/llm/qwen3.8-27b-mmproj-bf16.gguf"
          - "https://huggingface.co/huihui-ai/Huihui-Qwen3.8-27B-abliterated-GGUF/resolve/main/mmproj-model-bf16.gguf"
