---
- name: Setup LLM
  hosts: kosmos.xeno
  become: yes
  tasks:
    - name: Copy llama server config
      ansible.builtin.copy:
        src: "files/llama-server-configs/"
        dest: "/etc/llama.cpp.d/"
    - name: Link the llama server config for the model to use
      ansible.builtin.file:
        src: "/etc/llama.cpp.d/mistral-venice-edition.conf"
        dest: "/etc/llama.cpp.conf"
        state: link

    - name: Ensure llama.cpp server is enabled and started
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted
        name: llama.cpp
        enabled: yes

    - name: Ensure sysusers dir
      ansible.builtin.file:
        path: /usr/local/lib/sysusers.d
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Copy sysusers file
      ansible.builtin.copy:
        src: files/chainlit-chat.sysusers
        dest: /usr/local/lib/sysusers.d/chainlit-chat.conf
        owner: root
        group: root
        mode: '0644'
    - name: Ensure user
      ansible.builtin.systemd:
        state: restarted
        name: systemd-sysusers

    - name: Create venv
      ansible.builtin.pip:
        name:
          - openai
          - chainlit
          - beautifulsoup4
          - requests
        virtualenv: "/opt/llm/env"

    - name: Ensure app home dir
      ansible.builtin.file:
        path: /opt/llm/chat
        owner: cl_chat
        group: cl_chat
        mode: 0755
        state: directory

    - name: Copy encrypted credentials file
      ansible.builtin.copy:
        src: files/credentials-chat.toml
        dest: /opt/llm/chat/credentials.toml
        owner: cl_chat
        group: cl_chat
        mode: 0600

    - name: Copy prompt files
      ansible.builtin.copy:
        src: prompts
        dest: "/opt/llm/chat/"
    - name: Copy app file
      ansible.builtin.copy:
        src: files/chat.py
        dest: "/opt/llm/chat/chat.py"
    - name: Copy app service file
      ansible.builtin.copy:
        src: files/chainlit-chat.service
        dest: /etc/systemd/system/chainlit-chat.service
        owner: root
        group: root
        mode: '0644'
    - name: Ensure app service is enabled and started
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted
        name: chainlit-chat
        enabled: yes

    # SillyTavern
    - name: Install SillyTavern deps
      community.general.pacman:
        name:
          - npm
        state: present

    - name: Copy SillyTavern sysusers file
      ansible.builtin.copy:
        src: files/sillytavern.sysusers
        dest: /usr/local/lib/sysusers.d/sillytavern.conf
        owner: root
        group: root
        mode: '0644'
    - name: Ensure SillyTavern user
      ansible.builtin.systemd:
        state: restarted
        name: systemd-sysusers
    - name: Ensure sillytavern dir
      ansible.builtin.file:
        path: /opt/sillytavern
        owner: sillytavern
        group: sillytavern
        mode: 0755
        state: directory
    - name: Ensure sillytavern data dir
      ansible.builtin.file:
        path: /mnt/data/programs-data/sillytavern
        owner: sillytavern
        group: sillytavern
        mode: 0755
        state: directory
    - name: Clone SillyTavern app
      ansible.builtin.git:
        repo: 'https://github.com/SillyTavern/SillyTavern.git'
        dest: /opt/sillytavern/app
        version: release
      become_user: sillytavern
    - name: Copy SillyTavern config file
      ansible.builtin.copy:
        src: files/sillytavern.yaml
        dest: /opt/sillytavern/app/config.yaml
        owner: sillytavern
        group: sillytavern
        mode: '0600'
    - name: Copy SillyTavern service file
      ansible.builtin.copy:
        src: files/sillytavern.service
        dest: /etc/systemd/system/sillytavern.service
        owner: root
        group: root
        mode: '0644'
    - name: Ensure app service is enabled and started
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted
        name: sillytavern
        enabled: yes

- name: Setup HTTP proxy
  hosts: brighid.xeno
  become: yes
  tasks:
    - name: Copy Apache config
      ansible.builtin.copy:
        src: files/http-chat.conf
        dest: /etc/httpd/conf/extra/llm-chat.conf

    - name: Enable vhost
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#Include\s+conf/extra/llm-chat\.conf'
        insertafter: "Probably not exists"
        line: 'Include conf/extra/llm-chat.conf'

    - name: Copy SillyTavern Apache config
      ansible.builtin.copy:
        src: files/http-sillytavern.conf
        dest: /etc/httpd/conf/extra/sillytavern.conf

    - name: Enable SillyTavern vhost
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#Include\s+conf/extra/sillytavern\.conf'
        insertafter: "Probably not exists"
        line: 'Include conf/extra/sillytavern.conf'

    - name: Restart Apache
      ansible.builtin.systemd:
        state: restarted
        name: httpd
        enabled: yes
