---
# - name: Build llama.cpp
#   hosts: kosmos.xeno
#   become: yes
#   tasks:
#     - name: Copy PKGBUILD

- name: Setup LLM
  hosts: kosmos.xeno
  become: yes
  vars:
    profile: assistant
  tasks:
    - name: Copy llama server config
      ansible.builtin.copy:
        src: "llama-server-configs/{{ profile }}.conf"
        dest: "/etc/llama.cpp.conf"

    - name: Copy chat templates
      ansible.builtin.copy:
        src: "Mistral-Small-3.2-24B-Instruct-2506.jinja"
        dest: "/mnt/data/models/llm/"

    - name: Ensure sysusers dir
      ansible.builtin.file:
        path: /usr/local/lib/sysusers.d
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Copy sysusers file
      ansible.builtin.copy:
        src: chainlit-chat.sysusers
        dest: /usr/local/lib/sysusers.d/chainlit-chat.conf
        owner: root
        group: root
        mode: '0644'
    - name: Ensure user
      ansible.builtin.systemd:
        state: restarted
        name: systemd-sysusers

    - name: Create venv
      pip:
        name:
          - openai
          - chainlit
          - beautifulsoup4
          - requests
        virtualenv: "/opt/llm/env"

    - name: Ensure app home dir
      ansible.builtin.file:
        path: /opt/llm/chat
        owner: cl_chat
        group: cl_chat
        mode: 0755
        state: directory

    - name: Copy encrypted credentials file
      ansible.builtin.copy:
        src: credentials-chat.toml
        dest: /opt/llm/chat/credentials.toml
        owner: cl_chat
        group: cl_chat
        mode: 0600

    - name: Copy prompt files
      ansible.builtin.copy:
        src: prompts
        dest: "/opt/llm/chat/"
    - name: Copy app file
      ansible.builtin.copy:
        src: chat.py
        dest: "/opt/llm/chat/chat.py"
    - name: Copy app service file
      ansible.builtin.copy:
        src: chainlit-chat.service
        dest: /etc/systemd/system/chainlit-chat.service
        owner: root
        group: root
        mode: '0644'
    - name: Ensure app service is enabled and started
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted
        name: chainlit-chat
        enabled: yes

- name: Setup HTTP proxy
  hosts: brighid.xeno
  become: yes
  vars:
    profile: assistant
  tasks:
    - name: Copy Apache config
      ansible.builtin.copy:
        src: http-chat.conf
        dest: /etc/httpd/conf/extra/llm-chat.conf

    - name: Enable vhost
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#Include\s+conf/extra/llm-chat\.conf'
        insertafter: "Probably not exists"
        line: 'Include conf/extra/llm-chat.conf'

    - name: Restart Apache
      ansible.builtin.systemd:
        state: restarted
        name: httpd
        enabled: yes
