image_dir = "/var/lib/nspic/images"
static_dir = "/var/lib/nspic/static"
data_dir = "/var/lib/nspic"
listen_address = "127.0.0.1"
listen_port = 34740
password = "{{ upload_password }}"
image_pixel_size = 1280
thumb_pixel_size = 256
image_encoding = "Jpeg"
image_encoding_quality = 90

[site_info]
site_title = "MetroWind’s Pictures"
footnote = "All contents are under CC BY 4.0 (Attribution 4.0 International)."
url_domain = "http://photos.mws.rocks"
