data-dir: "/var/lib/planck-blog"
attachment-dir: "/var/lib/planck-blog/attachments"
listen-address: localhost
listen-port: 37254
client-id: planck
client-secret: "{{ client_secret }}"
openid-url-prefix: "https://auth.xeno.darksair.org/realms/xeno"
base-url: https://blog.mws.rocks
languages:
  - zh-CN
  - en-US
blog-title: Sky Watch
default-theme: planck-light
substitutions:
  nav-center: |
    <ul style="list-style: none; text-align: center; display: flex; align-items: center; gap: 24px;">
      <li style="height: 20px;">
        <a href="https://darksair.org/" aria-label="Home" color="currentcolor" style="display: inline-block; height: 20px;">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 486.988 486.988" width="20" height="20" style="display: inline-block;">
            <path fill="currentcolor"
                  d="M16.822,284.968h39.667v158.667c0,9.35,7.65,17,17,17h116.167c9.35,0,17-7.65,17-17V327.468h70.833v116.167
                    c0,9.35,7.65,17,17,17h110.5c9.35,0,17-7.65,17-17V284.968h48.167c6.8,0,13.033-4.25,15.583-10.483
                    c2.55-6.233,1.133-13.6-3.683-18.417L260.489,31.385c-6.517-6.517-17.283-6.8-23.8-0.283L5.206,255.785
                    c-5.1,4.817-6.517,12.183-3.967,18.7C3.789,281.001,10.022,284.968,16.822,284.968z M248.022,67.368l181.333,183.6h-24.367
                    c-9.35,0-17,7.65-17,17v158.667h-76.5V310.468c0-9.35-7.65-17-17-17H189.656c-9.35,0-17,7.65-17,17v116.167H90.489V267.968
                    c0-9.35-7.65-17-17-17H58.756L248.022,67.368z"/>
          </svg>
        </a>
      </li>
      <li><a href="https://blog.mws.rocks/">Blog</a></li>
      <li><a href="https://darksair.org/wiki/">Notes</a></li>
    </ul>
  after-post: |
    <script>
      var remark_config = {
        host: 'https://comments.mws.rocks',
        site_id: 'blog',
        components: ['embed'],
        max_shown_comments: 100,
        theme: 'light',
        locale: 'en',
        show_email_subscription: false,
        simple_view: true,
        no_footer: true
      }
    </script>
    <script>!function(e,n){for(var o=0;o<e.length;o++){var r=n.createElement("script"),c=".js",d=n.head||n.body;"noModule"in r?(r.type="module",c=".mjs"):r.async=!0,r.defer=!0,r.src=remark_config.host+"/web/"+e[o]+c,d.appendChild(r)}}(remark_config.components||["embed"],document);</script>
    <div id="remark42"></div>
