- name: Deploy Planck
  hosts: ssh.mws.rocks
  become: yes
  vars:
    iosevka_version: "31.7.1"
    client_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63343764356535393735306364616163356638616633383838383230383166333138663866386530
          3535303236343039613366363736373866323061306561330a333965646466303665633961366436
          61653338383732323138396564333035323439633866346638653437333865383635666335333833
          3166343835363536390a323865393437616133653436646465386136376135643866323636663939
          38323537346465626337353566663038363863313361323138396337633035303866326533313832
          3239306464316165393239666635373739346363656666393038
  tasks:
    - name: Download package
      ansible.builtin.get_url:
        url: "https://github.com/MetroWind/planck-blog/releases/latest/download/planck-blog-git-archlinux-x86_64.pkg.tar.zst"
        dest: "/tmp/planck-blog-git-archlinux-x86_64.pkg.tar.zst"

    - name: Install package
      community.general.pacman:
        name:
          - "/tmp/planck-blog-git-archlinux-x86_64.pkg.tar.zst"
        state: present

    - name: Remove package file
      ansible.builtin.file:
        path: "/tmp/planck-blog-git-archlinux-x86_64.pkg.tar.zst"
        state: absent

    - name: Create directory for monospace font
      ansible.builtin.file:
        path: /var/lib/planck-blog/statics/fonts/iosevka
        state: directory
        recurse: yes
        owner: planck
        group: planck

    - name: Download monospace font
      ansible.builtin.unarchive:
        src: "https://github.com/be5invis/Iosevka/releases/download/v{{ iosevka_version }}/PkgWebFont-IosevkaSS10-{{ iosevka_version }}.zip"
        dest: /var/lib/planck-blog/statics/fonts/iosevka
        remote_src: yes
        owner: planck
        group: planck

    - name: Create directory for text font
      ansible.builtin.file:
        path: /var/lib/planck-blog/statics/fonts/iosevka-etoile
        state: directory
        recurse: yes
        owner: planck
        group: planck

    - name: Download text font
      ansible.builtin.unarchive:
        src: "https://github.com/be5invis/Iosevka/releases/download/v{{ iosevka_version }}/PkgWebFont-IosevkaEtoile-{{ iosevka_version }}.zip"
        dest: /var/lib/planck-blog/statics/fonts/iosevka-etoile
        remote_src: yes
        owner: planck
        group: planck

    - name: Copy config
      ansible.builtin.template:
        src: config.yaml
        dest: /etc/planck-blog.yaml
        group: planck
        owner: planck
        mode: 0600

    - name: Copy Apache config
      ansible.builtin.copy:
        src: apache.conf
        dest: /etc/httpd/conf/vhosts/planck-blog.conf

    - name: Enable vhost
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#Include\s+conf/vhosts/planck-blog\.conf'
        insertafter: "Probably not exists"
        line: 'Include conf/vhosts/planck-blog.conf'

    - name: Restart Apache
      ansible.builtin.systemd:
        state: restarted
        name: httpd
        enabled: yes

    - name: Make sure service is running and enabled
      ansible.builtin.systemd:
        state: restarted
        name: planck-blog
        enabled: yes
        daemon_reload: yes
