# This playbook can be used to install a new forum, or overwrite an
# existing forum *with the same version*. This bypasses the
# installation wizard.
#
# NOTE: Don’t use this to upgrade!!!!!

- name: Deploy phpBB
  hosts: ssh.mws.rocks
  become: yes
  vars:
    phpbb_url: "https://download.phpbb.com/pub/release/3.3/3.3.12/phpBB-3.3.12.tar.bz2"
  tasks:
    - name: Install dependencies
      community.general.pacman:
        name:
          - sqlite
          - php
          - php-apache
          - php-sqlite
          # php-gd in Arch Linux doesn’t support AVIF & WEBP
          - php-imagick
          - libheif
        state: present

    - name: Configure PHP
      ansible.builtin.replace:
        path: /etc/php/php.ini
        regexp: ';date.timezone =.*'
        replace: 'date.timezone = America/Los_Angeles'

    - name: Configure PHP sqlite
      ansible.builtin.replace:
        path: /etc/php/php.ini
        regexp: ';extension=sqlite3'
        replace: 'extension=sqlite3'

    - name: Configure PHP sqlite PDO
      ansible.builtin.replace:
        path: /etc/php/php.ini
        regexp: ';extension=pdo_sqlite'
        replace: 'extension=pdo_sqlite'

    - name: Install phpBB files
      ansible.builtin.unarchive:
        src: "{{ phpbb_url }}"
        dest: /srv/http
        remote_src: yes
        owner: http
        group: http

    - name: Rename phpBB dir
      ansible.builtin.copy:
        src: /srv/http/phpBB3/
        dest: /srv/http/forum/
        remote_src: yes
        owner: http
        group: http

    - name: Remove orig phpBB dir
      ansible.builtin.file:
        path: /srv/http/phpBB3
        state: absent

    - name: Remove the install wizard dir
      ansible.builtin.file:
        path: /srv/http/forum/install
        state: absent

    - name: Create a directory for database
      ansible.builtin.file:
        path: /var/lib/phpbb
        state: directory
        mode: '0755'
        owner: http
        group: http

    - name: Link attachment dir
      ansible.builtin.include_tasks:
        file: link-dir.yaml
      vars:
        src_dir: /var/lib/phpbb/attachments
        link: /srv/http/forum/files

    - name: Link avatar gallery dir
      ansible.builtin.include_tasks:
        file: link-dir.yaml
      vars:
        src_dir: /var/lib/phpbb/avatars/gallery
        link: /srv/http/forum/images/avatars/gallery

    - name: Link avatar storage dir
      ansible.builtin.include_tasks:
        file: link-dir.yaml
      vars:
        src_dir: /var/lib/phpbb/avatars/upload
        link: /srv/http/forum/images/avatars/upload

    - name: Copy forum config
      ansible.builtin.copy:
        src: config.php
        dest: /srv/http/forum/config.php

    - name: Copy theme
      ansible.builtin.copy:
        src: themes/
        dest: /srv/http/forum/styles/
        owner: http
        group: http

    - name: Copy Apache config
      ansible.builtin.copy:
        src: apache.conf
        dest: /etc/httpd/conf/vhosts/forum.conf

    - name: Disable Apache MPM event
      ansible.builtin.replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^LoadModule mpm_event_module modules/mod_mpm_event\.so'
        replace: '#LoadModule mpm_event_module modules/mod_mpm_event.so'

    - name: Enable Apache MPM prefork module
      ansible.builtin.replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^# ?LoadModule mpm_prefork_module modules/mod_mpm_prefork\.so'
        replace: 'LoadModule mpm_prefork_module modules/mod_mpm_prefork.so'

    - name: Configure Apache PHP module
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#? ?LoadModule php_module modules/libphp\.so'
        insertafter: '^#? ?LoadModule .*'
        line: |
          LoadModule php_module modules/libphp.so
          AddHandler php-script .php

    - name: Include Apache PHP config
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#Include\s+conf/extra/php_module\.conf'
        insertafter: "Probably not exists"
        line: 'Include conf/extra/php_module.conf'

    - name: Enable vhost
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#Include\s+conf/vhosts/forum\.conf'
        insertafter: "Probably not exists"
        line: 'Include conf/vhosts/forum.conf'

    - name: Restart Apache
      ansible.builtin.systemd:
        state: restarted
        name: httpd
        enabled: yes
