---
- name: Setup Huginn DB
  ansible.builtin.import_playbook: init-db.yaml

- name: Install Huginn
  hosts: perdido.xeno
  become: yes
  vars:
    db_password: "{{ hostvars['brighid.xeno']['db_password'] }}"
  tasks:
    - name: Ensure docker and its python API is installed
      community.general.pacman:
        name:
          - docker
          - python-packaging
          - python-docker
        state: latest
    - name: Make sure docker is enabled and running
      ansible.builtin.systemd:
        state: started
        enabled: yes
        name: docker

    - name: Pull docker image
      community.docker.docker_image:
        name: ghcr.io/huginn/huginn
        source: pull

    - name: Copy env file to remote
      ansible.builtin.template:
        src: huginn.env
        dest: /etc/huginn.env
        owner: root
        group: wheel
        mode: '600'

    - name: Copy service file to remote
      ansible.builtin.copy:
        src: docker.huginn.service
        dest: /etc/systemd/system/docker.huginn.service
        owner: root
        group: wheel
        mode: '644'

    # Start service
    - name: Restart huginn
      ansible.builtin.systemd:
        state: restarted
        enabled: yes
        name: docker.huginn
        daemon_reload: yes

- name: Setup HTTP proxy
  hosts: brighid.xeno
  become: yes
  tasks:
    - name: Copy Apache config
      ansible.builtin.copy:
        src: httpd-vhost-huginn.conf
        dest: /etc/httpd/conf/extra/huginn.conf

    - name: Enable vhost
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#Include\s+conf/extra/huginn\.conf'
        insertafter: "Probably not exists"
        line: 'Include conf/extra/huginn.conf'

    - name: Restart Apache
      ansible.builtin.systemd:
        state: restarted
        name: httpd
        enabled: yes
