LoadModule proxy_uwsgi_module   modules/mod_proxy_uwsgi.so

<VirtualHost *:80>
    ServerName search.xeno.darksair.org
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</VirtualHost>
<VirtualHost *:443>
    ServerName search.xeno.darksair.org
    SSLCertificateFile /etc/letsencrypt/live/xeno.darksair.org/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/xeno.darksair.org/privkey.pem

    RewriteEngine On
    # add the trailing slash
    RedirectMatch  308 /searxng$ /searxng/

    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:45450/
    ProxyPassReverse / http://127.0.0.1:45450/

    # see flaskfix.py
    RequestHeader set X-Forwarded-Proto %{REQUEST_SCHEME}s
    RequestHeader set X-Script-Name /searxng

    # see botdetection/trusted_proxies.py
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader append X-Forwarded-For %{REMOTE_ADDR}s
</VirtualHost>
