- name: Build Stash
  hosts: amalthus.xeno
  tasks:
    - name: Download source
      ansible.builtin.git:
        repo: https://github.com/MetroWind/stash.git
        dest: ~/pkgs/stash

    - name: Build package
      ansible.builtin.command:
        cmd: makepkg -sr --noconfirm -f
        chdir: "~/pkgs/stash/package/archlinux"
        creates: "~/pkgs/stash/package/archlinux/stash-*-x86_64.pkg.tar.zst"

    - name: What package did I build?
      register: package_file_proc
      ansible.builtin.shell:
        cmd: "ls -1 stash-*-x86_64.pkg.tar.zst"
        chdir: ~/pkgs/stash/package/archlinux

    - set_fact:
        package_file: "{{ package_file_proc.stdout }}"

    - debug:
        msg: "Built package {{ package_file }}"

    - name: Fetch package to local
      ansible.builtin.fetch:
        src: "~/pkgs/stash/package/archlinux/{{ package_file }}"
        dest: /tmp/
        flat: yes

    - name: Remove build files
      ansible.builtin.file:
        path: ~/pkgs/stash
        state: absent

    - name: Remove other build files
      ansible.builtin.file:
        path: ~/.rustup
        state: absent

- name: Deploy Stash
  hosts: brighid.xeno
  become: yes
  vars:
    package_file: "{{ hostvars['amalthus.xeno']['package_file'] }}"
  tasks:
    - name: Copy package to remote
      ansible.builtin.copy:
        src: "/tmp/{{ package_file }}"
        dest: /tmp/

    # Install package from file doesn’t work until
    # https://github.com/ansible-collections/community.general/issues/4285
    # is upstream and is incorporated in Gentoo.
    - name: Install package
      ansible.builtin.command:
        cmd: "pacman -U --noconfirm /tmp/{{ package_file }}"

    - name: Chown of data dir
      ansible.builtin.file:
        path: /var/lib/stash
        owner: stash
        group: stash

    - name: Make sure Stash is running and enabled
      ansible.builtin.systemd:
        state: restarted
        name: stash
        enabled: yes
